book_site/books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),
    path('book/<int:pk>', views.BookDetail.as_view(), name='book_detail'),
    path('book/<int:pk>', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>', views.PublisherDetail.as_view(), name='publisher_detail'),

]

book_site/books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" />
    <title>{% block title %}My Amazing Site {% endblock %}</title>
</head>
<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Project_Home </a></li>
            <li><a href="/admin/"> Admin </a></li>
        </ul>
        <ul>
            <li><a href="/books/">Books_Home</a></li>
        </ul>
        {% endblock %}
        <br>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

book_site/books/templates/base_books.html
{% extends "base.html" %}

<title> {% block title %}Books Application Site {% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
    <li><a href="/books/">Books_Home</a></li>
</ul>

{% endblock %}

book_site/books/templates/books/author_detail.html
{% extends "base_book.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.salutation }}</p>
<li>Email : {{ object.email }}</li>
{% endblock content %}

book_site/books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Author List</h2>
    <ul>
        {% for author in object_list%}
            <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

book_site/books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" />
    <title>{% block title %}My Amazing Site {% endblock %}</title>
</head>
<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Project_Home </a></li>
            <li><a href="/admin/"> Admin </a></li>
        </ul>
        <ul>
            <li><a href="/books/">Books_Home</a></li>
        </ul>
        {% endblock %}
        <br>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

book_site/books/templates/books/base_books.html
{% extends "base.html" %}

<title> {% block title %}Books Application Site {% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
    <li><a href="/books/">Books_Home</a></li>
</ul>

{% endblock %}

book_site/books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
<h1>{{ object.title }}</h1>
<br>
<li> Authors:
    {% for author in object.authors.all %}
        {{ author }}
        {% if not forloop.last %}, {% else %}{% endif %}
    {% endfor %}
</li>

<li> Publisher: {{ object.publisher }}</li>
<li> Publication date: {{ object.publication_date }}</li>
{% endblock content %}

book_site/books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in object_list%}
            <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

book_site/books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books Management Systme</h2>
    <ul>
        {% for modelname in model_list %}
{% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
        <li><a href="{% url urlvar %}">{{ modelname }}</a> </li>
{% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}

book_site/books/templates/books/publisher_detail.html
{% extends "base_book.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.website }}</p>
<li>Address : {{ object.Address }}</li>
{% endblock content %}

book_site/books/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h2>shkim Django Applications</h2>
    <ul>
        {% for appname in app_list %}
{% with appname|add:":"|add:"index" as urlvar %}
            <li><a href="{% url urlvar %}">{{ appname}} </a></li>
{% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}